### ISSUE TITLE
Old versions of mini-chunks cause errors with current LBM.

### ISSUE THREAD

**Issue by Dushess** [SlimeVoid/LittleBlocks-FML#95]
So, the problem: I have building contains little blocks, it was created in 1.6.2, now using 1.7.10 i try to enter on map and see strange things. All blocks missing, exist only few entities, using memory fairly quickly raising to 99 and again, after closing map game getting stuck and then crashes.

Crash log contains this section:
[10:00:23] [Server thread/ERROR] [FML/]: A TileEntity littleblocks(net.slimevoid.littleblocks.tileentities.TileEntityLittleChunk) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.ArrayIndexOutOfBoundsException: 0
    at net.slimevoid.littleblocks.tileentities.TileEntityLittleChunk.getBlockByExtId(TileEntityLittleChunk.java:64) ~[TileEntityLittleChunk.class:?]
    at net.slimevoid.littleblocks.tileentities.TileEntityLittleChunk.removeInvalidBlocks(TileEntityLittleChunk.java:793) ~[TileEntityLittleChunk.class:?]
    at net.slimevoid.littleblocks.tileentities.TileEntityLittleChunk.func_145839_a(TileEntityLittleChunk.java:757) ~[TileEntityLittleChunk.class:?]
    at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:116) [aor.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:496) [aqk.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41) [ChunkIOProvider.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) [ChunkIOProvider.class:?]
    at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:?]
    at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:?]
    at
net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:78) [bsx.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) [bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]

Full log not saved, can upload later.

And question: little chunk format seems was updated for GV 1.7.2 and next, but can old little chunks be converted, or they will require LBM for 1.6.2/1.6.4 anyway?

**Comment by Tarig0** [comment]
changes to chunk data between 1.7 and 1.6 are massive. You'll have to start over at least for whats in the chunks

I would suggest if you really want to keep your world to retrieve all the blocks from LBs and store them in chests, upgrade to 1.7 and re-construct the chunks. Be sure to find ALL LB chunks and destory them before the upgrade

**Comment by Dushess** [comment]
I'm understand, updating mini-chunk structure is difficult right?
The reason is simple, that minichunks have many blocks, i made it for increase detail for few surfaces and add some elements, it looks like that.
![2014-11-21_23 33 29](https://cloud.githubusercontent.com/assets/15954961/11323486/e46efda0-912c-11e5-9173-338464e3018b.png)

Rebuilding it is possible and only way to do, but will take a lot of time.

**Comment by Tarig0** [comment]
wow I like nicely made cockpit panel
